import { useCallback, useEffect, useState } from 'react'
import { Check, Database, RefreshCw, X } from 'lucide-react'
import { getDevelopmentDatabaseStatus, type DevelopmentStatus } from './services/developmentService'
import { formatPrice } from './utils/format'

function formatDate(value: string) { return new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function label(value: string) { return value.replaceAll('_', ' ') }

export default function DevDatabasePage() {
  const [status, setStatus] = useState<DevelopmentStatus>()
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  const refresh = useCallback(async () => { setLoading(true); setError(''); try { setStatus(await getDevelopmentDatabaseStatus()) } catch { setStatus(undefined); setError('Could not connect to the development database verification API.') } finally { setLoading(false) } }, [])
  useEffect(() => { if (import.meta.env.DEV) void refresh(); else setLoading(false) }, [refresh])
  if (!import.meta.env.DEV) return <main className="dev-not-found"><h1>Not found</h1></main>
  return <main className="dev-database-page"><header className="dev-database-header"><div><p className="eyebrow">Local development tool</p><h1>Database Verification</h1><p>Read-only visibility into the repository currently serving this development app.</p></div><button className="solid-button dev-refresh" onClick={() => void refresh()} disabled={loading}><RefreshCw size={16} className={loading ? 'is-spinning' : ''} /> Refresh</button></header>{error ? <section className="dev-error"><X size={20} /><div><strong>MongoDB Not Connected</strong><p>{error}</p></div><button className="text-link" onClick={() => void refresh()}>Try again</button></section> : status && <><section className="dev-stat-grid"><div className="dev-stat"><span>Persistence mode</span><strong>{status.persistenceMode === 'mongo' ? 'MongoDB' : 'Memory'}</strong></div><div className="dev-stat"><span>Database</span><strong className={status.databaseConnected ? 'is-connected' : 'is-disconnected'}>{status.databaseConnected ? <><Check size={17} /> MongoDB Connected</> : <><X size={17} /> MongoDB Not Connected</>}</strong></div><div className="dev-stat"><span>Products</span><strong>{status.productCount}</strong></div><div className="dev-stat"><span>Orders</span><strong>{status.orderCount}</strong></div></section>{status.persistenceMode !== 'mongo' && <div className="dev-memory-note"><Database size={18} /><span>This application is currently using the in-memory repository, not MongoDB.</span></div>}<section className="dev-section"><div className="dev-section-heading"><div><p className="eyebrow">Latest records</p><h2>Recent Orders</h2></div><span>Last checked: {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date())}</span></div>{status.recentOrders.length === 0 ? <p className="dev-empty">No orders have been created yet.</p> : <div className="dev-table-wrap"><table className="dev-table"><thead><tr><th>Order ID</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th></tr></thead><tbody>{status.recentOrders.map((order) => <tr key={order.orderId}><td>{order.orderId}</td><td>{order.customerName}<small>{order.maskedPhone}</small></td><td>{formatPrice(order.total)}</td><td><strong>{label(order.paymentMethod)}</strong><small>{label(order.paymentStatus)}</small></td><td>{label(order.orderStatus)}</td><td>{formatDate(order.createdAt)}</td></tr>)}</tbody></table></div>}</section><section className="dev-section"><div className="dev-section-heading"><div><p className="eyebrow">Catalog snapshot</p><h2>Products</h2></div></div><div className="dev-table-wrap"><table className="dev-table"><thead><tr><th>Product ID</th><th>Name</th><th>SKU</th><th>Price</th><th>Stock</th></tr></thead><tbody>{status.recentProducts.map((product) => <tr key={product.productId}><td>{product.productId}</td><td>{product.name}</td><td>{product.sku}</td><td>{formatPrice(product.price)}</td><td>{product.stock}</td></tr>)}</tbody></table></div></section></>}</main>
}
